services:
  api:
    build: .
    container_name: ozmap-api
    ports:
      - '3333:3333'
    environment:
      PORT: 3333
      MONGO_URI: mongodb://admin:pass@mongodb:27017/ozmap_db?authSource=admin
      GOOGLE_GEOCODING_API_KEY: your_api_key_here
      GOOGLE_GEOCODING_COUNTRY: BR
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.13
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: ozmap_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
